pagopa/pagopa-receipt-pdf-notifier

helm/values-uat.yaml
- Updated UAT Helm values with proper IO base path
- Updated UAT helm values to reference proper IO services base path
- Required to reference proper IO API path
=> [PRDP-45] chore: updated UAT helm values

.gitignore, helm/Chart.yaml
=> fix: Chart yaml

helm/Chart.yaml
=> fix: chart version

.env.example, .github/workflows/code_review.yml, .gitignore, .identity/00_data.tf, .identity/02_application_action.tf, .identity/03_github_environment.tf, README.md, docker/README.md, docker/docker-compose.yml, docker/run_docker.sh, integration-test/run_integration_test.sh, integration-test/src/README.md, integration-test/src/config/.env.dev, integration-test/src/config/.env.local, integration-test/src/config/.env.uat, integration-test/src/features/receipt_pdf_datastore.feature, integration-test/src/package.json, integration-test/src/step_definitions/common.js, integration-test/src/step_definitions/receipt_pdf_datastore_step.js, integration-test/src/step_definitions/receipt_queue_client.js, integration-test/src/step_definitions/receipts_datastore_client.js, local.settings.json.example
- Introducing integration tests for notifier component
- Updated code review pipeline to enable int.test execution
=> [PRDP-37] feat: add integration tests

src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java
=> chore: change log levels

src/main/java/it/gov/pagopa/receipt/pdf/notifier/utils/ReceiptToIOUtils.java
=> fix: subject and markdown

src/main/java/it/gov/pagopa/receipt/pdf/notifier/utils/ReceiptToIOUtils.java
=> fix2 : markdown

src/main/java/it/gov/pagopa/receipt/pdf/notifier/exception/ErrorToNotifyException.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIOTest.java
- Fixed expected response status code for notify message request
- Improved log and exception handling
Local test
=> fix: Notify message response

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
=> [feat-remove-canary] Removed canary deploy

docker/run_docker.sh
- Updated docker_run.sh to properly check status code when starting docker
=> fix: Updated run_docker.sh to properly check info status code

.devops/performance-test-pipelines.yml, README.md, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, performance-test/README.md, performance-test/docker-compose.yaml, performance-test/nginx/nginx.conf, performance-test/run_performance_test.sh, performance-test/src/README.md, performance-test/src/dev.environment.json, performance-test/src/local.environment.json, performance-test/src/modules/common.js, performance-test/src/modules/datastore_client.js, performance-test/src/receipt_processor.js, performance-test/src/test-types/constant.json, performance-test/src/test-types/load.json, performance-test/src/test-types/spike.json, performance-test/src/test-types/stress.json, performance-test/src/uat.environment.json
- setup performance test project
- added azure pipeline to run performance tests
Performance test implementation
Run performance test in DEV-UAT environment
=> [PRDP-38] feat: Add performance tests

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
=> fix: Aks limits

.github/workflows/integration_test.yml, .identity/00_data.tf, .identity/03_github_environment.tf
Added slack web hook to integration test action
=> [PRDP-117] feat:Added slack webhook to integration test action

.github/workflows/integration_test.yml
=> [fix] Fixed integration-test action notification

helm/values-uat.yaml, performance-test/src/test-types/constant.json
=> Update for performance test

helm/Chart.lock, helm/Chart.yaml, helm/values-dev.yaml
=> fix: Upd helm chart

helm/values-prod.yaml, helm/values-uat.yaml
=> fix: Helm Uat and Prod

performance-test/src/test-types/constant.json, performance-test/src/uat.environment.json
=> feat: Update for performance test

Dockerfile, agent/config.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, pom.xml, src/main/java/it/gov/pagopa/receipt/pdf/notifier/Info.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/NotifierRetry.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIO.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/ReceiptToIOService.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java, src/main/resources/logback.xml, src/test/java/it/gov/pagopa/receipt/pdf/notifier/NotifierRetryTest.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIOTest.java
- added  `logback-classic`, `slf4j-api`, `logback-ecs-encoder`, `janino ` dependency
- added logback and otl environment variables in helm chart
- added otl agent in dockerfile
- refactored log
Show log on console, application insight and elastic
=> [PRDP-133] feat: Add slf4j and otl agent

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
- increase memory request and limit to 768Mi as datastore configuration
Increase memory request and limit to avoid scaling when idle
=> fix: Increase memory request and limit

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, src/main/java/it/gov/pagopa/receipt/pdf/notifier/Info.java, src/main/resources-filtered/application.properties, src/main/resources/logback.xml
- change service name
- removed useless environment variables
- upated info endpoint and unit tests
Use project name as service name
=> [PRDP-133] fix: Change log service name

src/main/java/it/gov/pagopa/receipt/pdf/notifier/entity/receipt/Receipt.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java
Added receipt's timestamps and timestamp "notified_at" valorization 
[Issue PRDP-135](https://pagopa.atlassian.net/browse/PRDP-135?atlOrigin=eyJpIjoiMmVkZGM2Mzg3MDMzNDNkMmJkMjQ5NTkzY2QwYzQzZjgiLCJwIjoiaiJ9)
=> [PRDP-135] Added receipt's timestamps

helm/values-dev.yaml, helm/values-uat.yaml
=> fix: Deploy

helm/values-uat.yaml
Lowered max replica to "1" in uat environment
=> [feat] Lowered max replica to 1

helm/values-prod.yaml, helm/values-uat.yaml
=> feat: Update helm uat

src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java
=> feat: updated ReceiptToIOServiceImpl to log unable to send status

integration-test/src/features/receipt_pdf_datastore.feature, integration-test/src/step_definitions/common.js, integration-test/src/step_definitions/receipt_pdf_datastore_step.js, performance-test/src/modules/common.js
- Update receipt model in integration test with the necessary field for building notification message subject and markdown
- Update receipt model in performance test with the necessary field for building notification message subject and markdown
=> [PRDP-153] fix: Update receipt model

helm/values-dev.yaml, helm/values-uat.yaml
=> chore: Switch to io-mock

src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java
- Deleted fiscal code from logs
[Issue PRDP-159](https://pagopa.atlassian.net/browse/PRDP-159?atlOrigin=eyJpIjoiZmFjODkyM2ViNjUwNGMzNzk3ZjM2ZDA0NGM1MDQ1MDMiLCJwIjoiaiJ9)
Fiscal codes were logged when specific errors occured
expected)
=> [PRDP-159] Deleted fiscal code from logs

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImplTest.java
- Removed base64 decoding
- Specified charset on environment variable read
Correctly show notification message
=> [PRDP-157] fix: Removed base64 encoding

helm/values-uat.yaml
=> chore: Enabled IO

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
- Set `LANG` environment variables to `UTF-8` in helm chart
Correctly show special characters in notification messages
=> [PRDP-157] fix: Notification message special characters

src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImplTest.java
- Add format to amount field
Show the amount in the notification message with italian format
=> [PRDP-166] feat: Amount in italian format

helm/values-prod.yaml
- Removed otl agent from prod config as temporary mitigation of linkage error using the agent in azure functions
=> chore: remove otl agent from prod configuration

.identity/env/prod/backend.tfvars, helm/values-uat.yaml
=> chore: Prdp 39 release receipt notifier

src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImpl.java
Added minimum and maximum fraction digits to currency format
Missing second decimal digits in currency value, it was displayed es. "0,4" instead of "0,40"
=> [fix-currency-format] fix: Changed currency format

src/main/java/it/gov/pagopa/receipt/pdf/notifier/entity/message/IOMessage.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/entity/receipt/ReasonError.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/entity/receipt/Receipt.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/ReceiptToIOService.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImplTest.java
- Set error messages on notify to have more specific detail on errors
- Refactor `verifyMessagesNotification` to simplify logic
- Updated unit tests
Improve errors on receipt
=> [PRDP-164] feat: Improve error messages

helm/values-prod.yaml
=> chore: Disable real api io messages for mock in prod

helm/values-prod.yaml
=> chore: Upd helm prod

.github/maven_code_review/action.yml, .github/workflows/code_review.yml, Dockerfile, docker/docker-compose.yml, docker/run_docker.sh, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, host.json, pom.xml
- Update java version in `pom.xml`
- Update java version in `Dockerfile`
- Add maven code review action to local project to specify java and maven version
- Fix `run_docker.sh` to correctly retrieve environment variables from helm chart
=> [PRDP-193] feat: Upgrade java version to jdk 17

.github/workflows/integration_test.yml, README.md, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, integration-test/src/step_definitions/common.js, performance-test/src/modules/common.js, pom.xml, src/main/java/it/gov/pagopa/receipt/pdf/notifier/client/PDVTokenizerClient.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/client/impl/PDVTokenizerClientImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/exception/ErrorToNotifyException.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/exception/PDVTokenizerException.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/exception/PDVTokenizerUnexpectedException.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/exception/ReceiptNotFoundException.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/model/tokenizer/ErrorMessage.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/model/tokenizer/ErrorResponse.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/model/tokenizer/InvalidParam.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/model/tokenizer/PiiResource.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/model/tokenizer/TokenResource.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/PDVTokenizerService.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/PDVTokenizerServiceRetryWrapper.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/PDVTokenizerServiceImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/PDVTokenizerServiceRetryWrapperImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/client/impl/PDVTokenizerClientImplTest.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/PDVTokenizerServiceImplTest.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/PDVTokenizerServiceRetryWrapperImplTest.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImplTest.java
- integrated PDV Tokenizer service
- added wrapper to handle tokenizer request retry for response with 429 status code
- added and updated unit test
Tokenize sensitive data
=> [PRDP-190] feat: Integrate PDV Tokenizer

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
=> chore: Fix double quote

src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/PDVTokenizerServiceImpl.java
- Fixed response mapping for 404 status code for `/tokens/search` and `/tokens/{token}/pii` endpoint
=> fix: Tokenizer error response mapping

docker/run_docker.sh, src/main/java/it/gov/pagopa/receipt/pdf/notifier/client/impl/PDVTokenizerClientImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/entity/receipt/enumeration/ReasonErrorCode.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/client/impl/PDVTokenizerClientImplTest.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImplTest.java
- updated reason error status code ad descripted in documentation
- fix pr smoke test
=> chore: Update reason error status codes

src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImplTest.java
- removed check for `cart[0].subject==null`
- set `subject` in notification message to `-` when `cart[0].subject==null`
Allow to notify receipt without subject
=> [PRDP-198] feat: Make subject field not mandatory

docker/run_docker.sh, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, src/main/java/it/gov/pagopa/receipt/pdf/notifier/Health.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/HealthTest.java
- added health function
Added dedicated endpoint for health check
=> feat: Add health function

helm/values-prod.yaml
=> upd default min replica

src/main/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIO.java
=> chore: Upd maxItemsPerInvocation

src/main/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIO.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/ReceiptToIOService.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/utils/ReceiptToIOUtils.java
=> feat: introducing parallelized stream in ReceiptToIO

src/main/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIO.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/utils/ReceiptToIOUtils.java
=> feat: Introducing parallel stream

src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImplTest.java
- added check on valid fiscal code before invoking getProfile API
- handled fiscal code not found response from getProfile API
=> fix: Add check on getProfile API

src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/PDVTokenizerServiceRetryWrapperImpl.java
- added retry on PDV tokenizer exception with code 800
=> feat: Added retry on PDV tokenizer exception

src/main/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIO.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIOTest.java
- added check to avoid notification logic on `ANONIMO` fiscal codes
=> [PRDP-303] fix: Exclude anonimo user from notify

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, src/main/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIO.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIOTest.java
=> [PRDP-306] feat: Disable notification when payer is defined

src/main/java/it/gov/pagopa/receipt/pdf/notifier/entity/receipt/Receipt.java
- Added isCart field to Receipt
[Issue PRDP-286](https://pagopa.atlassian.net/browse/PRDP-286?atlOrigin=eyJpIjoiZGM2YjAyYmU2ZjIzNDQzMGE4NWNlNGYwYTJhZGY1YjgiLCJwIjoiaiJ9)
=> [PRDP-286] Added isCart field to Receipt

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
=> chore: Enable payer notify

src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImplTest.java
- removed amount formatting
Amount already formatted
=> [PRDP-333] fix: Removed amount format

README.md, helm/values-prod.yaml, helm/values-uat.yaml, src/main/java/it/gov/pagopa/receipt/pdf/notifier/generated/model/ThirdPartyData.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImpl.java
- Added new env configuration_id for IO client CreateMessage API
[Issue PRDP-353](https://pagopa.atlassian.net/browse/PRDP-353?atlOrigin=eyJpIjoiZDk2Y2I3NzYzOWY3NDg5ZmE2MzcyZGQyZWU5NDc4YjAiLCJwIjoiaiJ9)
=> [PRDP-353] feat: Added new env configuration_id for IO client CreateMessage API

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, host.json, openapi/openapi-spec.yml, pom.xml, src/main/java/it/gov/pagopa/receipt/pdf/notifier/NotifierRetry.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIO.java
https://learn.microsoft.com/en-us/azure/azure-functions/migrate-cosmos-db-version-3-version-4?tabs=isolated-process&pivots=programming-language-java
Azure Functions upgrade and maintenance
- Tested in local and DEV environment
=> [PAGOPA-2017] chore: Upgrade ExtensionBundle

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, host.json, openapi/openapi-spec.yml, pom.xml, src/main/java/it/gov/pagopa/receipt/pdf/notifier/NotifierRetry.java
- update configuration and log verbose
- cost saving
- junit test
=> feat: [PAGOPA-2294] - log opt

.github/maven_code_review/action.yml, .github/workflows/integration_test.yml, helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi-spec.yml, pom.xml, src/main/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIO.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/client/ReceiptCosmosClient.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/client/impl/ReceiptCosmosClientImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/entity/message/IOMessage.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/exception/IoMessageNotFoundException.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/model/enumeration/UserNotifyStatus.java, src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/client/impl/ReceiptCosmosClientImplTest.java, src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImplTest.java
- updated io message output binding container to `receipts-io-messages-evt`
- added query on container `receipts-io-messages-evt` before notify to avoid duplicate notification
- updated unit tests
- bump cache GHA to latest version
- used self-hosted runner in integration test gha
[PIDM-355](https://pagopa.atlassian.net/browse/PIDM-355)
[PIDM-355]: https://pagopa.atlassian.net/browse/PIDM-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PIDM-355] fix: Improve duplicate notification check
